; CALCOLATRICE THE EASY WAY
include 'emu8086.inc'
ORG 100H

.DATA

FIRST_NUMBER DW 1 DUP(0)
SECOND_NUMBER DW 1 DUP(0)
MATH_SYMBOL DB 1 DUP(0)
RESULT DW 1 DUP(0)

.CODE

PRINT 'INSERT FIRST NUMBER: '           ; PRINT STRING 
CALL SCAN_NUM                           ; CALL SCAN NUMBER FUNCTION (INPUT GO IN CX)
MOV FIRST_NUMBER, CX                    ; MOVE CX TO FIRST_NUMBER
XOR CX, CX                              ; RESET CX TO 0
PUTC 10                                 ; PRINT A CHAR (10 = NEWLINE)
PUTC 13                                 ; PRINT A CHAR (13 = CRET)
PRINT 'INSERT SECOND NUMBER: '          ; PRINT STRING
CALL SCAN_NUM                           ; CALL SCAN NUMBER FUNCTION (INPUT GO IN CX)
MOV SECOND_NUMBER, CX                   ; MOVE CX TO FIRST_NUMBER

MATH:                                       
PUTC 10                                 ; PRINT A CHAR (10 = NEWLINE)
PUTC 13                                 ; PRINT A CHAR (13 = CRET)
PRINT 'INSERT MATH SYMBOL (+/*-): '     ; PRINT A STRING
MOV AH, 01H                             
INT 21H
CMP AL, 2AH                     ; CHECK IF IS * (2A)
    JE DO_MUL
    CMP AL, 2BH                 ; CHECK IF IS + (2B)
        JE DO_SUM
        CMP AL, 2DH             ; CHECK IF IS - (2D)
            JE DO_SUB
            CMP AL, 2FH         ; CHECK IF IS / (2F)
            JE DO_DIV
            JMP MATH
DO_MUL:
MOV MATH_SYMBOL, AL
MOV DX, FIRST_NUMBER
MOV AX, DX
MOV DX, 0
MOV DX, SECOND_NUMBER
MUL DX
JMP PRINT_IT

DO_DIV:
MOV MATH_SYMBOL, AL
MOV BX, FIRST_NUMBER
MOV AX, BX
MOV BX, 0
MOV BX, SECOND_NUMBER
DIV BX
JMP PRINT_IT

DO_SUM:
MOV MATH_SYMBOL, AL
MOV DX, FIRST_NUMBER
MOV AX, DX
MOV DX, 0
MOV DX, SECOND_NUMBER
ADD AX, DX
JMP PRINT_IT

DO_SUB:
MOV MATH_SYMBOL, AL
MOV DX, FIRST_NUMBER
MOV AX, DX
MOV DX, 0
MOV DX, SECOND_NUMBER
SUB AX, DX
JMP PRINT_IT

PRINT_IT:
PUTC 10
PUTC 13
PUTC 10
PUTC 13
PRINT 'SIGNED RESULT: '
CALL PRINT_NUM
PUTC 10
PUTC 13
PRINT 'UNSIGNED RESULT: '
CALL PRINT_NUM_UNS

DEFINE_SCAN_NUM
DEFINE_PRINT_NUM
DEFINE_PRINT_NUM_UNS
END