ORG 100H


.DATA

; ++ IF YOU WANT YOU CAN REPLACE THE CRET AND NEWL WITH
; ++# NEWLINE DB 10, 13, 36
; ++ AND PRINT IT LIKE THIS
; ++# MOV AH, 09H
; ++# MOV DX, NEWLINE
; ++# INT 21H
; ++ THIS WILL NOT MESS UP WITH BX LINE 02H DOES

.CODE

INPUT:
MOV AH, 01H ; +
INT 21H     ; +-> TAKE 1 CHAR AS ARGUMENT

CMP AL, 13 ; +
  JE SETUP ; +-> IF 13 (ENTER) PRINT THE TEXT
  
CMP AL, 08     ; +
  JE BACKSPACE ; +-> IF 8 (BACKSPACE) DELETE THE LETTER
  
MOV [SI], AL   ;+-> MOV INPUT INTO CELL
ADD SI, 1      ;+-> MOV TO THE NEXT CELL
JMP INPUT


BACKSPACE:
SUB SI, 1   ; +-> MOV TO THE PREVIOUS CELL 

MOV AH, 02H ; +
MOV DL, 32  ; |
INT 21H     ; +-> PRINT SPACE

MOV AH, 02H ; +
MOV DL, 08  ; |
INT 21H     ; +-> PRINT BACKSPACE
JMP INPUT

SETUP:
MOV BX, SI ; +-> SAVE THE LAST CELL INDEX IN BX 

MOV AH, 02H ; +
MOV DL, 10  ; |
INT 21H     ; +-> RESET THE CURSOR TO START

MOV AH, 02H ; +
MOV DL, 13  ; | 
INT 21H     ; +-> PRINT NEW LINE

MOV SI, 0   ; +-> RESET INDEX TO ZERO
  
PRINT:
CMP SI, BX ; +
  JE END   ; +-> IF SI IS EQUAL TO BX WE END THE PROGRAM 
  
MOV AH, 0EH  ;++ USING 02H TO PRINT WITH DL
MOV AL, [SI] ;++ MESS UP BX THAT KEEPS INCREMENTING
INT 10H      ;++ SO WE USE 0EH AND WE PRINT FROM AL
ADD SI, 1    ;++ MOVE TO THE NEXT CELL
JMP PRINT

END:
RET   